import {Inter} from 'next/font/google';
import SideBar from '../components/SideBar';

import '../globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-900`}>
        <div className="flex ">
          <div className="w-[18%]">
            <SideBar />
          </div>
          <div className="w-[81%] bg-black">{children}</div>
        </div>
      </body>
    </html>
  );
}
